### ISSUE TITLE
Volunteering for TypeDoc

### ISSUE THREAD

**Issue by ghost** [TypeStrong/discussions#3]
About a year ago I suggested to create a service that compiles TypeScript interfaces and declaration files from the NPM registry to a nice-looking website. Granted, it's been a while and I have been busy, but I'm willing to try it one last time this holiday. Is this still debatable? Would you accept pull requests and provide some web-hosting as has been discussed a long time ago? In order to get it working, I think that TypeDoc needs a bit of an upgrade. More specifically, issues like [these](https://github.com/TypeStrong/typedoc/issues/228) need to be solved. I'm willing to give it a try, but it might require me to do some patchwork.

Regards,
Sam

**Comment by blakeembrey** [comment]
Whatever you need, let me know! I'm happy to help in any way I can. I'm happy to accept PRs and let me know what you expect in terms of hosting (e.g. if it's primarily static, can we set it all up on AWS with Cloudfront and Lambda to queue generation?).

**Comment by ghost** [comment]
Cool, thanks! I'll start messing a bit with TypeDoc to see where that gets me. I didn't know of Lambda, but it seems like an ideal choice for this. I'll keep it in mind while programming.

**Comment by eteeselink** [comment]
@blakeembrey You could probably also consider hosting it for free on Netlify. They build the static site for you on their servers, using whatever static site generator you specify (including, say, a custom one that runs typedoc on everything in npmjs/@types). 

So if you make a cron job that triggers a netlify build every x hours/days, then you can skip lambda entirely and have everything with a single provider. Additionally they tend to love to sponsor dev stuff like this.

**Comment by blakeembrey** [comment]
@eteeselink I'm not sure how feasible it is to build a cron that'll build the entire NPM registry every _x_ hours, that's all. I'd suggest running it on demand and just caching instead. Whichever approach, I'm not the one in charge - I'll leave that to whoever implements it (right now that's @samvv).
